### ISSUE TITLE
Feature Request: Drawing and Form/Shapes

### ISSUE THREAD

**Issue by Teolone88** [lz100/drawer#3]
Hi,

I am trying to add the drawing feature but I find myself stuck as I am not able to re-use the already generated canvas.
Furthermore, the option to add shapes and forms could be easily implemented if I can tap into the canvas.

Would you be able to share with me how to append `isDrawingMode:` to TRUE or FALSE?

I am also trying to fit this [package ](https://github.com/feddelegrand7/fabricerin/blob/master/R/fabric_drawing.R) into the current drawer but I still have the same issue.

Best,

Teo

**Comment by lz100** [comment]
This is overlapping with the feature request of #1 . This will be added in the next version. I am closing this now. You can discuss the drawing feature and shapes in that issue. Feel free to reopen if you have other issues.
